import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 翻译字典
const translations = {
  zh: {
    // 通用
    'common.brainbox': 'BrainBox',
    'common.toggleColorMode': '切换主题',
    'common.translate': '翻译',
    'common.login': '登录',
    'common.chinese': '中文',
    'common.english': 'English',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.close': '关闭',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
          'common.search': '搜索',
      'common.loading': '加载中...',
      'common.latest': '最新',
    
    // 导航
    'nav.aiChat': 'AI 对话',
    'nav.history': '历史记录',
    'nav.aiDraw': 'AI 绘画',
    'nav.aiRead': 'AI 阅读',
    'nav.aiVideo': 'AI 视频',
    'nav.space': '个人空间',
    'nav.newChat': '新建对话',
    'nav.clearHistory': '清除历史',
    'nav.switchLanguage': '切换语言',
    'nav.login': '登录',
    
    // 认证相关
    'auth.login': '登录',
    'auth.logout': '退出登录',
    'auth.profile': '个人资料',
    'auth.settings': '设置',
    'auth.loginTitle': '登录到 BrainBox',
    'auth.loginDescription': '选择您喜欢的登录方式',
    'auth.loginWithGoogle': 'Google 登录',
    'auth.loginWithGithub': 'GitHub 登录',
    'auth.or': '或',
    'auth.continueAsGuest': '以访客身份继续',
    'auth.loginSuccess': '登录成功',
    'auth.logoutSuccess': '已退出登录',
    'auth.loginRequired': '需要登录',
    'auth.loginRequiredDesc': '请先登录以使用此功能',
    'auth.processing': '正在处理登录...',
    'auth.pleaseWait': '请稍候，即将跳转',
    'auth.success': '登录成功！',
    'auth.redirecting': '正在跳转到首页...',
    
    // AI聊天
    'chat.title': '一站使用全球AI大模型',
    'chat.placeholder': '开始和 {model} 聊天吧...',
    'chat.placeholderConversation': '与 {model} 对话...',
    'chat.helpWrite': '帮我写作',
    'chat.quickTranslate': '快速翻译',
    'chat.travelPlan': '旅游规划',
    'chat.scriptWrite': '影视剧本',
    'chat.thinking': 'AI正在思考中...',
    'chat.conversationInProgress': '进行中的对话',
    'chat.conversationSaved': '已保存状态',
    'chat.newConversation': '新建对话',
    
    // 模型选择
    'model.allModels': '所有模型',
    'model.regular': '常规模型',
    'model.advanced': '高级模型',
    'model.more': '更多',
    'model.badges.general': '通用',
    'model.badges.latest': '最新',
    'model.badges.fast': '快速',
    'model.badges.optimized': '优化',
    'model.badges.lightweight': '轻量',
    'model.badges.safe': '安全',
    'model.badges.recommended': '推荐',
    'model.badges.balanced': '平衡',
    'model.badges.newVersion': '新版',
    'model.badges.multimodal': '多模态',
    'model.badges.powerful': '超强',
    'model.badges.lightning': '闪电',
    'model.badges.reasoning': '推理',
    'model.badges.programming': '编程',
    'model.badges.math': '数学',
    'model.badges.opensource': '开源',
    'model.badges.ultra': '超大',
    
    // GPT模型描述
    'model.gpt35turbo.desc': 'OpenAI快速响应模型',
    'model.gpt4.desc': 'OpenAI强大的语言模型',
    'model.gpt4turbo.desc': '更快更智能的GPT-4版本',
    'model.gpt4o.desc': 'GPT-4优化版本',
    'model.gpt45turbo.desc': 'GPT-4.5最新版本',
    
    // Claude模型描述
    'model.claude3opus.desc': 'Claude最强大的模型',
    'model.claude3sonnet.desc': 'Claude平衡性能模型',
    'model.claude3haiku.desc': 'Claude快速响应模型',
    'model.claude35sonnet.desc': 'Claude 3.5 Sonnet版本',
    'model.claude35opus.desc': 'Claude 3.5 Opus版本',
    'model.claude37sonnet.desc': 'Claude 3.7 Sonnet版本',
    'model.claude37opus.desc': 'Claude 3.7 Opus版本',
    'model.claude4.desc': 'Claude最新一代模型',
    
    // Gemini模型描述
    'model.geminipro.desc': 'Google多模态AI模型',
    'model.geminiultra.desc': 'Google最先进的AI模型',
    'model.geminiflash.desc': 'Google快速响应模型',
    'model.gemini15pro.desc': 'Google 1.5 Pro版本',
    'model.gemini15flash.desc': 'Google 1.5快速版本',
    'model.gemini10ultra.desc': 'Google 1.0超强版本',
    'model.gemini25flash.desc': 'Google 2.5快速版本',
    'model.gemini25pro.desc': 'Google 2.5专业版本',
    
    // DeepSeek模型描述
    'model.deepseekr10528.desc': 'DeepSeek R1通用版本',
    'model.deepseekr1lite.desc': 'DeepSeek R1轻量版本',
    'model.deepseekv3.desc': 'DeepSeek最新一代模型',
    
    // Llama模型描述
    'model.llama31.desc': 'Meta开源大语言模型',
    'model.llama32ultra.desc': 'Meta最新开源大模型',
    'model.codellama.desc': 'Meta代码专用模型',
    'model.llama33.desc': 'Meta最新版本',
    'model.llama31405b.desc': 'Meta超大参数模型',
    'model.llama3170b.desc': 'Meta 70B大模型',
    'model.llama318b.desc': 'Meta 8B轻量版本',
    'model.llama370binstruct.desc': 'Meta 70B指令版本',
    'model.codellama70b.desc': 'Meta代码专用模型',
    
    // Grok模型描述
    'model.grok2.desc': 'xAI最新一代AI模型，具有强大的理解和推理能力',
    'model.grok15.desc': 'Grok快速响应版本，适合实时对话',
    'model.grokbeta.desc': 'xAI最新测试版本，具有前沿AI能力',
    'model.grok2pro.desc': 'Grok 2专业版本，强化推理能力',
    
    // Qwen模型描述
    'model.qwenmax.desc': '阿里云最强大的AI模型，具有卓越的中文理解能力',
    'model.qwenturbo.desc': 'Qwen高效版本，适合快速响应需求',
    'model.qwenplus.desc': 'Qwen增强版本，在各项任务中表现出色',
    'model.qwenmaxpro.desc': '阿里云最强大的AI模型专业版',
    
    // AI绘画
    'draw.title': 'AI 绘画',
    'draw.describe': '描述你想要的图片',
    'draw.placeholder': '请详细描述你想要生成的图片，例如：一只可爱的小猫坐在花园里，阳光明媚，油画风格',
    'draw.settings': '生成设置',
    'draw.style': '风格',
    'draw.size': '尺寸',
    'draw.generate': '生成图片',
    'draw.generating': '生成中...',
    'draw.result': '生成结果',
    'draw.regenerate': '重新生成',
    'draw.download': '下载',
    'draw.resultPlaceholder': '生成的图片将显示在这里',
    'draw.generatingText': '正在生成图片...',
    'draw.styleRealistic': '写实风格',
    'draw.styleAnime': '动漫风格',
    'draw.styleOilPainting': '油画风格',
    'draw.styleWatercolor': '水彩风格',
    'draw.styleSketch': '素描风格',
    'draw.sizeSquare': '1:1 (正方形)',
    'draw.sizePortrait': '3:4 (竖版)',
    'draw.sizeLandscape': '4:3 (横版)',
    'draw.sizeWidescreen': '16:9 (宽屏)',
    'draw.sizeMobilePortrait': '9:16 (手机竖屏)',
    
    // AI绘画模式和上传功能
    'draw.mode': '生成模式',
    'draw.textToImage': '文生图',
    'draw.imageToImage': '图生图',
    'draw.uploadImage': '上传参考图片',
    'draw.uploadDesc': '支持 JPG、PNG 格式',
    'draw.dragDrop': '拖拽图片到此处或点击上传',
    'draw.replaceImage': '更换图片',
    'draw.removeImage': '移除图片',
    'draw.referenceImage': '参考图片',
    'draw.strength': '参考强度',
    'draw.strengthDesc': '数值越高，生成图片越接近参考图片',
    'draw.deleteImage': '删除图片',
    'draw.downloadSuccess': '图片下载成功',
    'draw.downloadError': '下载失败',
    'draw.downloadErrorDesc': '请稍后重试',
    'draw.favorite': '收藏',
    'draw.favorited': '已收藏',
    'draw.favoriteSuccess': '已收藏图片',
    'draw.unfavoriteSuccess': '已取消收藏',
    
    // AI阅读
    'read.title': 'AI阅读',
    'read.desc': '🤖 智能文档分析助手，让AI为您深度解读文档内容',
    'read.selectSource': '选择文本来源',
    'read.uploadFile': '上传文件',
    'read.uploadDesc': '支持PDF、Word、TXT',
    'read.webLink': '网页链接',
    'read.webDesc': '自动提取网页内容',
    'read.pasteText': '粘贴文本',
    'read.pasteDesc': '直接粘贴文本内容',
    'read.settings': '阅读设置',
    'read.goal': '设置阅读目标（可选）',
    'read.startReading': '开始阅读',
    'read.preview': '内容预览',
    'read.previewPlaceholder': '请选择或输入要阅读的文本...',
    'read.unsupportedFileType': '不支持的文件类型',
    'read.uploadSupportedFiles': '请上传PDF、Word或TXT文件',
    'read.fetchingWebContent': '正在获取网页内容...',
    'read.webContentFetched': '网页内容获取成功',
    'read.webContentSample': '这里是网页文本内容...',
    'read.startAnalysis': '开始智能分析',
    'read.analysisDesc': '已解析 {count} 个字符，点击"开始智能分析"进入对话模式',
    'read.characters': '字符',
    'read.processingDocument': '正在解析文档...',
    'read.uploadPlaceholder': '上传文档后，内容将在此处显示',
    'read.supportedFormats': '支持 TXT、PDF、DOCX 格式',
    'read.intelligentAnalysis': '智能文档分析',
    'read.documentAnalysisDesc': '基于您的文档内容进行智能问答 ({count} 字符)',
    'read.backToUpload': '返回上传',
    'read.you': '您',
    'read.aiAssistant': 'AI助手',
    'read.copyContent': '复制内容',
    'read.bookmark': '收藏',
    'read.aiAnalyzing': 'AI正在分析文档内容...',
    'read.inputPlaceholder': '请输入您想要从文档中提取的信息，例如：总结主要内容、提取关键观点等...',
    'read.analyzing': '分析中',
    'read.send': '发送',
    'read.newSession': '新建阅读会话',
    'read.newSessionDesc': '已清空当前内容，可以上传新文档',
    'read.cancel': '取消',
    'read.getContent': '获取内容',
    'read.pasteTextPlaceholder': '请将要分析的文本内容粘贴到这里...',
    'read.confirmAdd': '确认添加',
    'read.onlySupport10Page': '仅支持10页以内文档',
    'read.onlySupport10Pages': '仅支持10页以内文档，超出将无法预览或分析',
    

    // 历史记录
    'history.title': '历史记录',
    'history.search': '搜索历史记录...',
    'history.noHistory': '暂无历史记录',
    'history.clearAll': '清除所有',
    'history.rename': '重命名',
    'history.delete': '删除',
    'history.renamePlaceholder': '请输入新的对话名称',
    'history.deleteConfirm': '删除历史记录',
    'history.deleteConfirmText': '你确定要删除这条历史记录吗？此操作无法撤销。',
    'history.clearAllConfirm': '清除所有历史记录',
    'history.clearAllConfirmText': '你确定要清除所有历史记录吗？这将删除所有的聊天、绘画和阅读记录，此操作无法撤销。',
    'history.deleteSuccess': '历史记录已删除',
    'history.clearSuccess': '所有历史记录已清除',
    'history.multiSelect': '多选',
    'history.selectAll': '全选',
    'history.cancelSelect': '取消全选',
    'history.restored': '已恢复',
    'history.documentChat': '文档对话',
    'history.chat': '聊天',
    'history.records': '条记录',
    'history.cancel': '取消',
    'history.deleteSelected': '删除选中',
    'history.batchDeleteConfirm': '确认批量删除',
    'history.batchDeleteConfirmText': '您确定要删除选中的 {count} 条历史记录吗？此操作无法撤销。',
    'history.batchDeleteSuccess': '已删除 {count} 条历史记录',
    'history.renameTitle': '重命名历史记录',
    'history.renamePlaceholderNew': '请输入新的标题',
    'history.renameSuccess': '重命名成功',
    'history.moreOptions': '更多选项',
    'history.startNewChat': '开始新对话',
    'history.pleaseLoginFirst': '请先登录查看历史记录',
    
    // 个人空间
    'space.title': '个人空间',
    'space.profile': '个人资料',
    'space.settings': '设置',
    'space.usage': '使用统计',
    'space.username': '用户名',
    'space.email': 'user@example.com',
    'space.editProfile': '编辑资料',
    'space.chatCount': '对话次数',
    'space.imageCount': '生成图片',
    'space.readCount': '阅读文档',
    'space.favoriteCount': '收藏数量',
    'space.recentActivity': '最近活动',
    'space.myFavorites': '我的收藏',
    'space.multiSelect': '多选',
    'space.favoriteTextToImage': '收藏的文生图',
    'space.favoriteTextToVideo': '收藏的文生视频',
    'space.favoriteImageToImage': '收藏的图生图',
    'space.favoriteImageEdit': '收藏的图像编辑',
    'space.favoriteImageToVideo': '收藏的图生视频',
    'space.generatedImage': '生成的图片:',
    'space.generatedVideo': '生成的视频:',
    'space.editedImage': '编辑后的图片:',
    'space.originalImage': '原始图片:',
    'space.referenceImage': '参考图片:',
    'space.prompt': '提示词:',
    'space.externalLinkExpire': '外链可能过期',
    'space.permanentlySaved': '永久保存',
    'space.videoStorageNote': '💾 带有"永久保存"标签的视频已保存到服务器，不会过期。⚠️ 外链视频可能会在一段时间后失效。',
    'space.selectAll': '全选',
    'space.unselectAll': '取消全选',
    'space.clearAll': '清空所有',
    'space.noRecentActivity': '暂无最近活动',
    'space.noFavorites': '暂无收藏内容',
    'space.favoriteConversation': '收藏的对话',
    'space.favoriteImage': '收藏的图片',
    'space.favoriteDocument': '收藏的文档',
    'space.deleteFavorite': '删除收藏',
    'space.favoriteRemoved': '已取消收藏',
    'space.favoriteType': '类型',
    'space.favoriteTime': '收藏时间',
    'space.imageLoadFailed': '图片加载失败',
    'space.imageLinkExpired': '图片链接已失效',
    'space.videoPreviewUnavailable': '视频暂时无法预览',
    'space.imageExpired': '图片链接已过期',
    'space.aiChat': 'AI对话',
    'space.imageGeneration': '图片生成',
    'space.documentReading': '文档阅读',
    'space.favoriteChat': '收藏的对话',
    'space.hoursAgo': '小时前',
    'space.yesterday': '昨天',
    'space.daysAgo': '天前',
    'space.aiDiscussion': '关于AI发展的讨论',
    'space.futureCityscape': '未来城市景观',
    'space.mlPaper': '机器学习论文',
    
    // 翻译功能
    'translate.title': 'AI 翻译助手',
    'translate.description': '支持多种语言互译，智能识别语言类型',
    'translate.autoDetect': '自动检测',
    'translate.sourceLang': '源语言',
    'translate.targetLang': '目标语言',
    'translate.sourceText': '原文',
    'translate.targetText': '译文',
    'translate.sourcePlaceholder': '请输入要翻译的文本...',
    'translate.targetPlaceholder': '翻译结果将显示在这里...',
    'translate.swapLanguages': '交换语言',
    'translate.startTranslate': '开始翻译',
    'translate.result': '翻译结果',
    
    // 写作功能
    'write.title': '帮我写作',
    'write.placeholder': '目标撰写的主题',
    'write.tone': '语气',
    'write.length': '长度',
    'write.language': '语言',
    'write.tones.formal': '正式的',
    'write.tones.casual': '随意的',
    'write.tones.friendly': '友好的',
    'write.tones.professional': '专业的',
    'write.lengths.short': '短',
    'write.lengths.medium': '中',
    'write.lengths.long': '长',
    'write.languages.zhCN': '中文(简体)',
    'write.languages.en': 'English',
    'write.topics.xiaohongshu': '小红书',
    'write.topics.douyin': '抖音脚本',
    'write.topics.moments': '朋友圈',
    'write.topics.weibo': '微博',
    'write.topics.marketing': '营销文案',
    'write.topics.brainstorm': '头脑风暴',
    'write.topics.outline': '大纲',
    'write.topics.monthlyReport': '月报',
    'write.topics.weeklyReport': '周报',
    
    // 快速翻译功能
    'quickTranslate.title': '快速翻译',
    'quickTranslate.placeholder': '来说点什么吧...',
    'quickTranslate.translateTo': '翻译为',
    'quickTranslate.tone': '语气',
    'quickTranslate.tones.spoken': '口语',
    'quickTranslate.tones.written': '书面语',
    'quickTranslate.tones.formal': '正式',
    'quickTranslate.tones.business': '商务',
    
    // 旅行规划功能
    'travel.title': '旅行规划',
    'travel.destination': '目的地',
    'travel.days': '出行天数',
    'travel.interests': '兴趣点',
    'travel.details': '请补充更多细节，例如出行人数、特殊偏好等...',
    'travel.budget': '预算',
    'travel.pace': '节奏',
    'travel.budgets.economy': '经济',
    'travel.budgets.comfort': '舒适',
    'travel.budgets.luxury': '豪华',
    'travel.paces.relaxed': '轻松',
    'travel.paces.normal': '常规',
    'travel.paces.intensive': '紧凑',
    'travel.interests.food': '美食',
    'travel.interests.shopping': '购物',
    'travel.interests.history': '历史古迹',
    'travel.interests.nature': '自然风光',
    'travel.interests.hiking': '徒步',
    'travel.interests.museum': '博物馆',

    
    // 网页摘要功能
    'summary.title': '网页摘要',
    'summary.placeholder': '输入或粘贴网页链接...',
    'summary.description': '将自动提取网页内容进行总结',
    
    // 新建会话提示
    'session.newChatStarted': '已开始新的聊天会话',
    'session.newDrawStarted': '已开始新的绘图会话',
    'session.newReadStarted': '已开始新的阅读会话',
    'session.newButton': '新建',
    
    // 绘图提示
    'draw.sizeNote': '注：9:16适合手机壁纸，可能在桌面显示时较长',
    
    // 图像编辑
    'draw.edit': '编辑图片',
    'draw.editing': '编辑中...',
    'draw.editPlaceholder': '描述您想要进行的编辑，例如：将女孩的头发改为红色',
    
    // AI视频生成
    'video.title': '视频生成',
    'video.textToVideo': '文生视频',
    'video.imageToVideo': '图生视频',
    'video.description': '使用AI生成高质量视频',
    'video.descriptionPlaceholder': '请描述您想要的视频内容，例如：一只小猫在草地上玩耍',
    'video.selectStyle': '选择风格',
    'video.aspectRatio': '宽高比',
    'video.aspectRatio.16-9': '16:9 (横向)',
    'video.aspectRatio.9-16': '9:16 (竖向)',
    'video.aspectRatio.1-1': '1:1 (正方形)',
    'video.aspectRatio.4-3': '4:3 (传统)',
    'video.aspectRatio.16-9.desc': '适合电脑观看',
    'video.aspectRatio.9-16.desc': '适合手机观看',
    'video.generateVideo': '生成视频',
    'video.aspectRatio.1-1.desc': '适合社交媒体',
    'video.aspectRatio.4-3.desc': '传统电视宽高比',
    'video.duration': '视频时长',
    'video.seconds': '秒',
    'video.generate': '生成视频',
    'video.generating': '生成中...',
    'video.progress': '进度',
    'video.prompt': '视频描述',
    'video.promptDesc': '请描述您想要的视频内容，例如：一只小猫在草地上玩耍',
    'video.selectModel': '选择模型',
    'video.referenceImage': '参考图片',
    'video.uploadImage': '上传图片',
    'video.uploadDesc': '支持 JPG、PNG 格式',
    'video.motionStrength': '运动强度',
    'video.motionStrengthDesc': '数值越高，图片中的元素运动越明显',
    'video.motionDescription': '运动描述',
    'video.motionPlaceholder': '描述图片中的元素应该如何运动，例如：树叶轻轻摇摆，水面波光粼粼，人物缓慢走动...',
    'video.durationNote': '💡 视频时长固定为5秒',
    'video.preview': '预览',
    'video.previewArea': '视频预览区域',
    'video.previewDesc': '生成的视频将在这里显示',
    'video.download': '下载视频',
    'video.deleteVideo': '删除视频',
    'video.deleteImage': '删除图片',
    'video.addFavorite': '添加收藏',
    'video.removeFavorite': '取消收藏',
    'video.regularModel': '常规模型',
    'video.googleVeo3Model': 'Google Veo 3 模型',
    'video.assistantGreeting': '您好！我是Google Veo 3 AI视频助手',
    'video.assistantDesc': '我可以帮您生成高质量的AI视频。请描述您想要的视频内容，我会为您创造精彩的视觉效果！',
    'video.exampleText': '示例：一只橙色的小猫在阳光明媚的草地上快乐地奔跑',
    'video.style': '风格',
    'video.speed': '速度',
          'video.googleVeo3Title': 'Google Veo 3视频',
      'video.googleVeo3Chat': 'Google Veo 3 AI对话',
      'video.dashscopeDesc': '阿里云DashScope AI视频生成技术，支持高质量视频创作',
    'video.feature5SecHD': '✨ 5秒高清视频',
    'video.featureCinemaQuality': '🎬 电影级画质',
    'video.featurePreciseControl': '🎯 精准控制',
    'video.featureText2Video': '💬 支持文生视频',
    'video.videoSize': '🎬 视频尺寸',
    'video.promptPlaceholder': '✨ 描述您想要的视频场景...',
    'video.speeds.slow': '慢速',
    'video.speeds.normal': '正常',
    'video.speeds.fast': '快速',
    'video.styles.realistic': '写实',
    'video.styles.realisticDesc': '逼真的视频效果',
    'video.styles.anime': '动漫',
    'video.styles.animeDesc': '日式动漫风格',
    'video.styles.cartoon': '卡通',
    'video.styles.cartoonDesc': '可爱的卡通效果',
    'video.styles.cinematic': '电影',
    'video.styles.cinematicDesc': '电影级别的视觉效果',
    'video.styles.fantasy': '奇幻',
    'video.styles.fantasyDesc': '魔幻奇幻效果',
    'video.styles.movie': '电影',
    'video.styles.cyberpunk': '赛博朋克',
    'video.styles.cyberpunkDesc': '未来科技风格',
    
    // 个人空间翻译
    'space.videos': '生成视频',
    'space.videoGeneration': '视频生成',
    'space.favoriteVideo': '收藏视频',
    
    // 会员相关翻译
    'membership.subscribe': '开通会员',
    'membership.title': '会员中心',
    'membership.back': '返回',
    'membership.supportMultiModel': '支持多种AI模型',
    'membership.slogan': '解锁全部AI能力',
    'membership.subtitle': '选择适合您的计划，开启无限可能',
    'membership.annual': '年付费',
    'membership.monthly': '月付费',
    'membership.annualTip': '年付费更优惠，省80%费用',
    'membership.monthlyTip': '月付费灵活订阅，随时取消',
    'membership.free': '普通会员',
    'membership.annualMember': '年付费会员',
    'membership.monthlyMember': '月付费会员',
    'membership.freePrice': '免费',
    'membership.annualPrice': '$9.9',
    'membership.annualOrigin': '原价202.8元/年',
    'membership.annualSpecial': '特惠118.8/年',
    'membership.monthlyPrice': '$16.9',
    'membership.period': '/月',
    'membership.popular': '最受欢迎',
    'membership.freeDesc': '适合个人体验5次/每天',
    'membership.annualDesc': '年付更优惠，省41%',
    'membership.monthlyDesc': '灵活订阅，按月付费',
    'membership.annualFeatures': '获取150000积分, 额外赠送30000积分, 常规模型无限次对话, 高级模型可对话500次, 生成图片100张, 生成视频25条, 优先客服支持',
    'membership.monthlyFeatures': '获取10000积分, 常规模型无限次对话, 高级模型可对话500次, 生成图片100张, 生成视频25条, 标准客服支持',
    'membership.freeFeatures': '每日5次AI对话, 基础模型访问, 标准响应速度, 基础功能使用',
    'membership.useNow': '立即使用',
    'membership.subscribeAnnual': '立即订阅年付费',
    'membership.subscribeMonthly': '立即订阅月付费',
    'membership.switchSuccess': '切换成功',
    'membership.switchToFree': '您已切换到普通会员',
    'membership.paySuccess': '支付成功',
    'membership.paySuccessDesc': '您已成功订阅{plan}',
    'membership.payFailed': '支付失败',
    'membership.payFailedDesc': '请检查支付信息或稍后重试',
    'membership.switchDesc': '您已切换到当前会员类型',

    // AI对话-影视剧本
    'script.title': '影视剧本创作',
    'script.scriptType': '剧本类型',
    'script.genreType': '题材类型',
    'script.movie': '电影剧本',
    'script.shortFilm': '短片剧本',
    'script.tvSeries': '电视剧本',
    'script.webSeries': '网剧剧本',
    'script.drama': '剧情剧本',
    'script.comedy': '喜剧剧本',
    'script.action': '动作剧本',
    'script.romance': '爱情剧本',
    'script.scifi': '科幻剧本',
    'script.horror': '恐怖剧本',
    'script.thriller': '惊悚剧本',
    'script.fantasy': '奇幻剧本',
    'script.creative': '剧本创意',
    'script.creativePlaceholder': '请描述你的剧本创意，比如：一个关于时间旅行的爱情故事，主角意外回到过去遇见了年轻的恋人...',
    'script.creating': '正在创作',
    'script.genre': '题材',
    'script.pleaseInputIdea': '请输入剧本创意',
    'script.requestFailed': '请求失败',
    'script.pleaseTryAgain': '请稍后重试',

    // 年付费会员权益
    'membership.annualFeature1': '获取150000积分',
    'membership.annualFeature2': '额外赠送30000积分',
    'membership.annualFeature3': '常规模型无限次对话',
    'membership.annualFeature4': '高级模型可对话500次',
    'membership.annualFeature5': '生成图片100张',
    'membership.annualFeature6': '生成视频25条',
    'membership.annualFeature7': '优先客服支持',
    // 月付费会员权益
    'membership.monthlyFeature1': '获取10000积分',
    'membership.monthlyFeature2': '常规模型无限次对话',
    'membership.monthlyFeature3': '高级模型可对话500次',
    'membership.monthlyFeature4': '生成图片100张',
    'membership.monthlyFeature5': '生成视频25条',
    'membership.monthlyFeature6': '标准客服支持',
    // 免费会员权益
    'membership.freeFeature1': '每日5次AI对话',
    'membership.freeFeature2': '基础模型访问',
    'membership.freeFeature3': '标准响应速度',
    'membership.freeFeature4': '基础功能使用',

    // 积分和免费额度相关翻译
    'credits.consume': '消耗',
    'credits.credits': '积分',
    'credits.consumeCredits': '消耗{cost}积分',
    'credits.remainingFreeChats': '剩余免费对话',
    'credits.remainingFreeDocs': '剩余免费文档',
    'credits.remainingFreePDF': '剩余免费PDF',
    'credits.remainingFreeImages': '剩余免费图片',
    'credits.remainingFreeVideos': '剩余免费视频',
    'credits.remainingCredits': '剩余积分',
    'credits.recharge': '充值积分',
    'credits.freeQuotaFormat': '{remaining}/{total}',
    
    // 按钮上的费用显示
    'ui.costCredits': '消耗{cost}积分',
    'ui.remainingFree': '剩余免费{type}：{remaining}/{total}',
    'ui.freeChat': '对话',
    'ui.freeDocument': '文档',
    'ui.freePDF': 'PDF',
    'ui.freeImage': '图片',
    'ui.freeVideo': '视频',
    
    // 选择器标签翻译
    'selector.tone': '语气',
    'selector.length': '长度',
    'selector.language': '语言',
    'selector.translateTo': '翻译为',
    'selector.budget': '预算',
    'selector.pace': '节奏',
  },
  en: {
    // 通用
    'common.brainbox': 'BrainBox',
    'common.toggleColorMode': 'Toggle Theme',
    'common.translate': 'Translate',
    'common.login': 'Login',
    'common.chinese': 'Chinese',
    'common.english': 'English',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
          'common.search': 'Search',
      'common.loading': 'Loading...',
      'common.latest': 'Latest',
    
    // 导航
    'nav.aiChat': 'AI Chat',
    'nav.history': 'History',
    'nav.aiDraw': 'AI Draw',
    'nav.aiRead': 'AI Read',
    'nav.aiVideo': 'AI Video',
    'nav.space': 'Personal Space',
    'nav.newChat': 'New Chat',
    'nav.clearHistory': 'Clear History',
    'nav.switchLanguage': 'Switch Language',
    'nav.login': 'Login',
    
    // 认证相关
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.profile': 'Profile',
    'auth.settings': 'Settings',
    'auth.loginTitle': 'Login to BrainBox',
    'auth.loginDescription': 'Quick login with third-party account to enjoy full features',
    'auth.loginWithGoogle': 'Login with Google',
    'auth.loginWithGithub': 'Login with GitHub',
    'auth.or': 'or',
    'auth.continueAsGuest': 'Continue as guest',
    'auth.loginSuccess': 'Login successful',
    'auth.logoutSuccess': 'Logged out successfully',
    'auth.loginRequired': 'Login Required',
    'auth.loginRequiredDesc': 'Please login to view your profile.',
    'auth.processing': 'Processing login...',
    'auth.pleaseWait': 'Please wait, redirecting...',
    'auth.success': 'Login successful!',
    'auth.redirecting': 'Redirecting to homepage...',
    
    // AI聊天
    'chat.title': 'One-stop access to global AI models',
    'chat.placeholder': 'Start chatting with {model}...',
    'chat.placeholderConversation': 'Chat with {model}...',
    'chat.helpWrite': 'Help Write',
    'chat.quickTranslate': 'Quick Translate',
    'chat.travelPlan': 'Travel Plan',
    'chat.scriptWrite': 'Script Writing',
    'chat.thinking': 'AI is thinking...',
    'chat.conversationInProgress': 'Conversation in progress',
    'chat.conversationSaved': 'Conversation saved',
    'chat.newConversation': 'New Conversation',
    
    // 模型选择
    'model.allModels': 'All Models',
    'model.regular': 'Regular Models',
    'model.advanced': 'Advanced Models',
    'model.more': 'More',
    'model.badges.general': 'General',
    'model.badges.latest': 'Latest',
    'model.badges.fast': 'Fast',
    'model.badges.optimized': 'Optimized',
    'model.badges.lightweight': 'Lightweight',
    'model.badges.safe': 'Safe',
    'model.badges.recommended': 'Recommended',
    'model.badges.balanced': 'Balanced',
    'model.badges.newVersion': 'New Version',
    'model.badges.multimodal': 'Multimodal',
    'model.badges.powerful': 'Powerful',
    'model.badges.lightning': 'Lightning',
    'model.badges.reasoning': 'Reasoning',
    'model.badges.programming': 'Programming',
    'model.badges.math': 'Math',
    'model.badges.opensource': 'Open Source',
    'model.badges.ultra': 'Ultra',
    
    // GPT模型描述
    'model.gpt35turbo.desc': 'OpenAI fast response model',
    'model.gpt4.desc': 'OpenAI powerful language model',
    'model.gpt4turbo.desc': 'Faster and smarter GPT-4 version',
    'model.gpt4o.desc': 'GPT-4 optimized version',
    'model.gpt45turbo.desc': 'GPT-4.5 latest version',
    
    // Claude模型描述
    'model.claude3opus.desc': 'Claude\'s most powerful model',
    'model.claude3sonnet.desc': 'Claude balanced performance model',
    'model.claude3haiku.desc': 'Claude quick response model',
    'model.claude35sonnet.desc': 'Claude 3.5 Sonnet version',
    'model.claude35opus.desc': 'Claude 3.5 Opus version',
    'model.claude37sonnet.desc': 'Claude 3.7 Sonnet version',
    'model.claude37opus.desc': 'Claude 3.7 Opus version',
    'model.claude4.desc': 'Claude next generation model',
    
    // Gemini模型描述
    'model.geminipro.desc': 'Google multimodal AI model',
    'model.geminiultra.desc': 'Google\'s most advanced AI model',
    'model.geminiflash.desc': 'Google quick response model',
    'model.gemini15pro.desc': 'Google 1.5 Pro version',
    'model.gemini15flash.desc': 'Google 1.5 fast version',
    'model.gemini10ultra.desc': 'Google 1.0 ultra version',
    'model.gemini25flash.desc': 'Google 2.5 fast version',
    'model.gemini25pro.desc': 'Google 2.5 professional version',
    
    // DeepSeek模型描述
    'model.deepseekr10528.desc': 'DeepSeek R1 general version',
    'model.deepseekr1lite.desc': 'DeepSeek R1 lightweight version',
    'model.deepseekv3.desc': 'DeepSeek latest generation model',
    
    // Llama模型描述
    'model.llama31.desc': 'Meta open source large language model',
    'model.llama32ultra.desc': 'Meta latest open source large model',
    'model.codellama.desc': 'Meta code dedicated model',
    'model.llama33.desc': 'Meta latest version',
    'model.llama31405b.desc': 'Meta ultra parameter model',
    'model.llama3170b.desc': 'Meta 70B large model',
    'model.llama318b.desc': 'Meta 8B lightweight version',
    'model.llama370binstruct.desc': 'Meta 70B instruction version',
    'model.codellama70b.desc': 'Meta code specialized model',
    
    // Grok模型描述 - 英文
    'model.grok2.desc': 'xAI\'s latest generation AI model with powerful understanding and reasoning capabilities',
    'model.grok15.desc': 'Grok fast response version suitable for real-time conversations',
    'model.grokbeta.desc': 'xAI latest test version with cutting-edge AI capabilities',
    'model.grok2pro.desc': 'Grok 2 professional version with enhanced reasoning capabilities',
    
    // Qwen模型描述 - 英文
    'model.qwenmax.desc': 'Alibaba Cloud\'s most powerful AI model with excellent Chinese understanding capabilities',
    'model.qwenturbo.desc': 'Qwen efficient version suitable for fast response needs',
    'model.qwenplus.desc': 'Qwen enhanced version that excels in various tasks',
    'model.qwenmaxpro.desc': 'Alibaba Cloud\'s most powerful AI model professional version',
    
    // AI绘画
    'draw.title': 'AI Draw',
    'draw.describe': 'Describe the image you want',
    'draw.placeholder': 'Please describe the image you want to generate in detail, e.g.: A cute cat sitting in a garden, sunny day, oil painting style',
    'draw.settings': 'Generation Settings',
    'draw.style': 'Style',
    'draw.size': 'Size',
    'draw.generate': 'Generate Image',
    'draw.generating': 'Generating...',
    'draw.result': 'Result',
    'draw.regenerate': 'Regenerate',
    'draw.download': 'Download',
    'draw.resultPlaceholder': 'Generated image will appear here',
    'draw.generatingText': 'Generating image...',
    'draw.styleRealistic': 'Realistic Style',
    'draw.styleAnime': 'Anime Style',
    'draw.styleOilPainting': 'Oil Painting Style',
    'draw.styleWatercolor': 'Watercolor Style',
    'draw.styleSketch': 'Sketch Style',
    'draw.sizeSquare': '1:1 (Square)',
    'draw.sizePortrait': '3:4 (Portrait)',
    'draw.sizeLandscape': '4:3 (Landscape)',
    'draw.sizeWidescreen': '16:9 (Widescreen)',
    'draw.sizeMobilePortrait': '9:16 (Mobile Portrait)',
    
    // AI绘画模式和上传功能
    'draw.mode': 'Generation Mode',
    'draw.textToImage': 'Text to Image',
    'draw.imageToImage': 'Image to Image',
    'draw.uploadImage': 'Upload Reference Image',
    'draw.uploadDesc': 'Support JPG, PNG formats',
    'draw.dragDrop': 'Drag image here or click to upload',
    'draw.replaceImage': 'Replace Image',
    'draw.removeImage': 'Remove Image',
    'draw.referenceImage': 'Reference Image',
    'draw.strength': 'Reference Strength',
    'draw.strengthDesc': 'Higher values make generated image closer to reference',
    'draw.deleteImage': 'Delete Image',
    'draw.downloadSuccess': 'Image downloaded successfully',
    'draw.downloadError': 'Download failed',
    'draw.downloadErrorDesc': 'Please try again later',
    'draw.favorite': 'Favorite',
    'draw.favorited': 'Favorited',
    'draw.favoriteSuccess': 'Image favorited',
    'draw.unfavoriteSuccess': 'Removed from favorites',
    
    // AI阅读
    'read.title': 'AI reading',
    'read.desc': '🤖 AI document analysis assistant, let AI help you deeply understand the document content',
    'read.selectSource': 'Select text source',
    'read.uploadFile': 'Upload file',
    'read.uploadDesc': 'Support PDF, Word, TXT',
    'read.webLink': 'Web link',
    'read.webDesc': 'Automatically extract web content',
    'read.pasteText': 'Paste text',
    'read.pasteTextPlaceholder': 'Please paste the text content you want to analyze here...',
    'read.pasteDesc': 'Directly paste text content',
    'read.settings': 'Reading settings',
    'read.goal': 'Set reading goal (optional)',
    'read.startReading': 'Start reading',
    'read.preview': 'Content preview',
    'read.previewPlaceholder': 'Please select or enter the text you want to read...',
    'read.unsupportedFileType': 'Unsupported file type',
    'read.uploadSupportedFiles': 'Please upload PDF, Word, or TXT files',
    'read.fetchingWebContent': 'Fetching web content...',
    'read.webContentFetched': 'Web content fetched successfully',
    'read.webContentSample': 'Here is the web text content...',
    'read.startAnalysis': 'Start Analysis',
    'read.analysisDesc': 'Parsed {count} characters, click "Start Analysis" to enter chat mode',
    'read.characters': 'characters',
    'read.processingDocument': 'Processing document...',
    'read.uploadPlaceholder': 'Content will appear here after uploading the document',
    'read.supportedFormats': 'Support TXT, PDF, DOCX formats',
    'read.intelligentAnalysis': 'Intelligent Document Analysis',
    'read.documentAnalysisDesc': 'Intelligent question answering based on your document content ({count} characters)',
    'read.backToUpload': 'Back to Upload',
    'read.you': 'You',
    'read.aiAssistant': 'AI Assistant',
    'read.copyContent': 'Copy Content',
    'read.bookmark': 'Bookmark',
    'read.aiAnalyzing': 'AI is analyzing document content...',
    'read.inputPlaceholder': 'Enter the information you want to extract from the document, e.g.: Summarize the main content, extract key points, etc...',
    'read.analyzing': 'Analyzing',
    'read.send': 'Send',
    'read.newSession': 'New Reading Session',
    'read.newSessionDesc': 'Current content cleared, can upload new document',
    'read.cancel': 'Cancel',
    'read.getContent': 'Get Content',
    'read.confirmAdd': 'Confirm Add',
    'read.onlySupport10Page': 'Only supports documents within 10 pages',
    'read.onlySupport10Pages': 'Only supports documents within 10 pages, exceeded will not be able to preview or analyze',
    
    // 历史记录
    'history.title': 'History',
    'history.search': 'Search history...',
    'history.noHistory': 'No history yet',
    'history.clearAll': 'Clear All',
    'history.rename': 'Rename',
    'history.delete': 'Delete',
    'history.renamePlaceholder': 'Enter new conversation name',
    'history.deleteConfirm': 'Delete History',
    'history.deleteConfirmText': 'Are you sure you want to delete this history record? This action cannot be undone.',
    'history.clearAllConfirm': 'Clear All History',
    'history.clearAllConfirmText': 'Are you sure you want to clear all history? This will delete all chat, drawing, and reading records. This action cannot be undone.',
    'history.deleteSuccess': 'History deleted successfully',
    'history.clearSuccess': 'All history cleared successfully',
    'history.multiSelect': 'Multi-select',
    'history.selectAll': 'Select All',
    'history.cancelSelect': 'Cancel Select All',
    'history.restored': 'Restored',
    'history.documentChat': 'document chat',
    'history.chat': 'chat',
    'history.records': 'records',
    'history.cancel': 'Cancel',
    'history.deleteSelected': 'Delete Selected',
    'history.batchDeleteConfirm': 'Confirm Batch Delete',
    'history.batchDeleteConfirmText': 'Are you sure you want to delete the selected {count} history records? This action cannot be undone.',
    'history.batchDeleteSuccess': 'Deleted {count} history records',
    'history.renameTitle': 'Rename History Record',
    'history.renamePlaceholderNew': 'Enter new title',
    'history.renameSuccess': 'Rename successful',
    'history.moreOptions': 'More Options',
    'history.startNewChat': 'Start New Chat',
    'history.pleaseLoginFirst': 'Please login first to view history',
    
    // 个人空间
    'space.title': 'Personal Space',
    'space.profile': 'Profile',
    'space.settings': 'Settings',
    'space.usage': 'Usage Statistics',
    'space.username': 'Username',
    'space.email': 'user@example.com',
    'space.editProfile': 'Edit Profile',
    'space.chatCount': 'Chat Count',
    'space.imageCount': 'Generated Images',
    'space.readCount': 'Read Documents',
    'space.favoriteCount': 'Favorites',
    'space.recentActivity': 'Recent Activity',
    'space.myFavorites': 'My Favorites',
    'space.multiSelect': 'Multi-select',
    'space.favoriteTextToImage': 'Favorite Text-to-Image',
    'space.favoriteTextToVideo': 'Favorite Text-to-Video',
    'space.favoriteImageToImage': 'Favorite Image-to-Image',
    'space.favoriteImageEdit': 'Favorite Image Edit',
    'space.favoriteImageToVideo': 'Favorite Image-to-Video',
    'space.generatedImage': 'Generated Image:',
    'space.generatedVideo': 'Generated Video:',
    'space.editedImage': 'Edited Image:',
    'space.originalImage': 'Original Image:',
    'space.referenceImage': 'Reference Image:',
    'space.prompt': 'Prompt:',
    'space.externalLinkExpire': 'External link may expire',
    'space.permanentlySaved': 'Permanently saved',
    'space.videoStorageNote': '💾 Videos marked as "permanently saved" are stored on the server and won\'t expire. ⚠️ External links may expire after some time.',
    'space.selectAll': 'Select All',
    'space.unselectAll': 'Unselect All',
    'space.clearAll': 'Clear All',
    'space.noRecentActivity': 'No recent activity',
    'space.noFavorites': 'No favorites yet',
    'space.favoriteConversation': 'Favorite Chat',
    'space.favoriteImage': 'Favorite Image',
    'space.favoriteDocument': 'Favorite Document',
    'space.deleteFavorite': 'Delete Favorite',
    'space.favoriteRemoved': 'Removed from favorites',
    'space.favoriteType': 'Type',
    'space.favoriteTime': 'Favorite Time',
    'space.imageLoadFailed': 'Image load failed',
    'space.imageLinkExpired': 'Image link expired',
    'space.videoPreviewUnavailable': 'Video preview unavailable',
    'space.imageExpired': 'Image link expired',
    'space.aiChat': 'AI Chat',
    'space.imageGeneration': 'Image Generation',
    'space.documentReading': 'Document Reading',
    'space.favoriteChat': 'Favorite Chat',
    'space.hoursAgo': 'hours ago',
    'space.yesterday': 'yesterday',
    'space.daysAgo': 'days ago',
    'space.aiDiscussion': 'Discussion about AI development',
    'space.futureCityscape': 'Future cityscape',
    'space.mlPaper': 'Machine learning paper',
    
    // 翻译功能
    'translate.title': 'AI Translation Assistant',
    'translate.description': 'Support multi-language translation with intelligent language detection',
    'translate.autoDetect': 'Auto Detect',
    'translate.sourceLang': 'Source Language',
    'translate.targetLang': 'Target Language',
    'translate.sourceText': 'Source Text',
    'translate.targetText': 'Translation',
    'translate.sourcePlaceholder': 'Enter text to translate...',
    'translate.targetPlaceholder': 'Translation result will appear here...',
    'translate.swapLanguages': 'Swap Languages',
    'translate.startTranslate': 'Start Translation',
    'translate.result': 'Translation Result',
    
    // 写作功能
    'write.title': 'Help Write',
    'write.placeholder': 'Target writing topic',
    'write.tone': 'Tone',
    'write.length': 'Length',
    'write.language': 'Language',
    'write.tones.formal': 'Formal',
    'write.tones.casual': 'Casual',
    'write.tones.friendly': 'Friendly',
    'write.tones.professional': 'Professional',
    'write.lengths.short': 'Short',
    'write.lengths.medium': 'Medium',
    'write.lengths.long': 'Long',
    'write.languages.zhCN': '中文(简体)',
    'write.languages.en': 'English',
    'write.topics.xiaohongshu': 'Xiaohongshu',
    'write.topics.douyin': 'Douyin Script',
    'write.topics.moments': 'Moments',
    'write.topics.weibo': 'Weibo',
    'write.topics.marketing': 'Marketing Copy',
    'write.topics.brainstorm': 'Brainstorm',
    'write.topics.outline': 'Outline',
    'write.topics.monthlyReport': 'Monthly Report',
    'write.topics.weeklyReport': 'Weekly Report',
    
    // 快速翻译功能
    'quickTranslate.title': 'Quick Translate',
    'quickTranslate.placeholder': 'Say something...',
    'quickTranslate.translateTo': 'Translate to',
    'quickTranslate.tone': 'Tone',
    'quickTranslate.tones.spoken': 'Spoken',
    'quickTranslate.tones.written': 'Written',
    'quickTranslate.tones.formal': 'Formal',
    'quickTranslate.tones.business': 'Business',
    
    // 旅行规划功能
    'travel.title': 'Travel Plan',
    'travel.destination': 'Destination',
    'travel.days': 'Travel Days',
    'travel.interests': 'Interests',
    'travel.details': 'Please add more details, such as number of travelers, special preferences, etc...',
    'travel.budget': 'Budget',
    'travel.pace': 'Pace',
    'travel.budgets.economy': 'Economy',
    'travel.budgets.comfort': 'Comfort',
    'travel.budgets.luxury': 'Luxury',
    'travel.paces.relaxed': 'Relaxed',
    'travel.paces.normal': 'Normal',
    'travel.paces.intensive': 'Intensive',
    'travel.interests.food': 'Food',
    'travel.interests.shopping': 'Shopping',
    'travel.interests.history': 'Historical Sites',
    'travel.interests.nature': 'Natural Scenery',
    'travel.interests.hiking': 'Hiking',
    'travel.interests.museum': 'Museum',
    
    // 网页摘要功能
    'summary.title': 'Web Summary',
    'summary.placeholder': 'Enter or paste web link...',
    'summary.description': 'Will automatically extract and summarize web content',
    
    // 新建会话提示
    'session.newChatStarted': 'New chat session started',
    'session.newDrawStarted': 'New drawing session started',
    'session.newReadStarted': 'New reading session started',
    'session.newButton': 'New',
    
    // 绘图提示
    'draw.sizeNote': 'Note: 9:16 is suitable for mobile wallpapers, may appear long on desktop',
    
    // 图像编辑
    'draw.edit': 'Edit Image',
    'draw.editing': 'Editing...',
    'draw.editPlaceholder': 'Describe the edits you want to make, e.g.: Change the girl\'s hair to red',
    
    // AI视频生成
    'video.title': 'Video Generation',
    'video.textToVideo': 'Text to Video',
    'video.imageToVideo': 'Image to Video',
    'video.description': 'Generate high-quality videos with AI',
    'video.descriptionPlaceholder': 'Please describe the content of the video you want to generate, e.g.: A kitten running in the moonlight...',
    'video.selectStyle': 'Select Style',
    'video.aspectRatio': 'Aspect Ratio',
    'video.aspectRatio.16-9': '16:9 (Landscape)',
    'video.aspectRatio.9-16': '9:16 (Portrait)',
    'video.aspectRatio.1-1': '1:1 (Square)',
    'video.aspectRatio.4-3': '4:3 (Traditional)',
    'video.aspectRatio.16-9.desc': 'Suitable for computer viewing',
    'video.aspectRatio.9-16.desc': 'Suitable for mobile viewing',
    'video.generateVideo': 'Generate Video',
    'video.aspectRatio.1-1.desc': 'Suitable for social media',
    'video.aspectRatio.4-3.desc': 'Traditional TV aspect ratio',
    'video.duration': 'Video Duration',
    'video.seconds': 'Seconds',
    'video.generate': 'Generate Video',
    'video.generating': 'Generating...',
    'video.progress': 'Progress',
    'video.prompt': 'Video Description',
    'video.promptDesc': 'Please describe the video content you want, e.g.: A small cat playing on the grass',
    'video.selectModel': 'Select Model',
    'video.referenceImage': 'Reference Image',
    'video.uploadImage': 'Upload Image',
    'video.uploadDesc': 'Support JPG, PNG formats',
    'video.motionStrength': 'Motion Strength',
    'video.motionStrengthDesc': 'Higher values make the elements in the image move more obviously',
    'video.motionDescription': 'Motion Description',
    'video.motionPlaceholder': 'Describe how elements in the image should move, e.g.: Leaves gently swaying, water ripples, person slowly walking...',
    'video.durationNote': '💡 Video duration is fixed at 5 seconds',
    'video.preview': 'Preview',
    'video.previewArea': 'Video Preview Area',
    'video.previewDesc': 'Generated video will be displayed here',
    'video.download': 'Download Video',
    'video.deleteVideo': 'Delete Video',
    'video.deleteImage': 'Delete Image',
    'video.addFavorite': 'Add Favorite',
    'video.removeFavorite': 'Remove Favorite',
    'video.regularModel': 'Regular Model',
    'video.googleVeo3Model': 'Google Veo 3 Model',
    'video.assistantGreeting': 'Hello! I\'m Google Veo 3 AI Video Assistant',
    'video.assistantDesc': 'I can help you generate high-quality AI videos. Please describe the video content you want, and I\'ll create amazing visual effects for you!',
    'video.exampleText': 'Example: An orange kitten running happily on a sunny grass field',
    'video.style': 'Style',
    'video.speed': 'Speed',
          'video.googleVeo3Title': 'Google Veo 3 Video',
      'video.googleVeo3Chat': 'Google Veo 3 AI Chat',
      'video.dashscopeDesc': 'Alibaba Cloud DashScope AI video generation technology, supports high-quality video creation',
    'video.feature5SecHD': '✨ 5-second HD video',
    'video.featureCinemaQuality': '🎬 Cinema-grade quality',
    'video.featurePreciseControl': '🎯 Precise control',
    'video.featureText2Video': '💬 Text-to-video support',
    'video.videoSize': '🎬 Video Size',
    'video.promptPlaceholder': '✨ Describe your desired video scene...',
    'video.speeds.slow': 'Slow',
    'video.speeds.normal': 'Normal',
    'video.speeds.fast': 'Fast',
    'video.styles.realistic': 'Realistic',
    'video.styles.realisticDesc': 'Realistic video effect',
    'video.styles.anime': 'Anime',
    'video.styles.animeDesc': 'Japanese anime style',
    'video.styles.cartoon': 'Cartoon',
    'video.styles.cartoonDesc': 'Cute cartoon effect',
    'video.styles.cinematic': 'Cinematic',
    'video.styles.cinematicDesc': 'Cinematic level visual effect',
    'video.styles.fantasy': 'Fantasy',
    'video.styles.fantasyDesc': 'Magic fantasy effect',
    'video.styles.movie': 'Movie',
    'video.styles.cyberpunk': 'Cyberpunk',
    'video.styles.cyberpunkDesc': 'Future tech style',
    
    // 个人空间翻译
    'space.videos': 'Generated Videos',
    'space.videoGeneration': 'Video Generation',
    'space.favoriteVideo': 'Favorite Video',
    
    // 会员相关翻译
    'membership.subscribe': 'Subscribe',
    'membership.title': 'Membership Center',
    'membership.back': 'Back',
    'membership.supportMultiModel': 'Support multiple AI models',
    'membership.unlockAll': 'Unlock all AI capabilities',
    'membership.choosePlan': 'Choose your plan and unlock unlimited possibilities',
    'membership.slogan': 'Unlock all AI capabilities',
    'membership.subtitle': 'Choose your plan and unlock unlimited possibilities',
    'membership.annual': 'Annual',
    'membership.monthly': 'Monthly',
    'membership.annualTip': 'Annual payment is more cost-effective, save 80%',
    'membership.monthlyTip': 'Monthly subscription, cancel anytime',
    'membership.free': 'Free Member',
    'membership.annualMember': 'Annual Member',
    'membership.monthlyMember': 'Monthly Member',
    'membership.freePrice': 'Free',
    'membership.annualPrice': '$9.9',
    'membership.annualOrigin': 'Original ¥202.8/year',
    'membership.annualSpecial': 'Special ¥118.8/year',
    'membership.monthlyPrice': '$16.9',
    'membership.period': '/mo',
    'membership.popular': 'Most Popular',
    'membership.freeDesc': 'Ideal for personal trial, 5 times/day',
    'membership.annualDesc': 'Annual payment saves 41%',
    'membership.monthlyDesc': 'Flexible monthly subscription',
    'membership.annualFeatures': 'Get 150,000 credits, Extra 30,000 credits, Unlimited chats with regular models, 500 chats with advanced models, Generate 100 images, Generate 25 videos, Priority customer support',
    'membership.monthlyFeatures': 'Get 10,000 credits, Unlimited chats with regular models, 500 chats with advanced models, Generate 100 images, Generate 25 videos, Standard customer support',
    'membership.freeFeatures': '5 AI chats per day, Basic model access, Standard response speed, Basic features',
    'membership.useNow': 'Use Now',
    'membership.subscribeAnnual': 'Subscribe Annual',
    'membership.subscribeMonthly': 'Subscribe Monthly',
    'membership.switchSuccess': 'Switched successfully',
    'membership.switchToFree': 'You have switched to Free Member',
    'membership.paySuccess': 'Payment successful',
    'membership.paySuccessDesc': 'You have successfully subscribed to {plan}',
    'membership.payFailed': 'Payment failed',
    'membership.payFailedDesc': 'Please check your payment info or try again later',
    'membership.switchDesc': 'You have switched to the current membership type',

    // AI对话-影视剧本
    'script.title': 'Script Writing',
    'script.scriptType': 'Script Type',
    'script.genreType': 'Genre Type',
    'script.movie': 'Movie Script',
    'script.shortFilm': 'Short Film Script',
    'script.tvSeries': 'TV Series Script',
    'script.webSeries': 'Web Series Script',
    'script.drama': 'Drama',
    'script.comedy': 'Comedy',
    'script.action': 'Action',
    'script.romance': 'Romance',
    'script.scifi': 'Sci-Fi',
    'script.horror': 'Horror',
    'script.thriller': 'Thriller',
    'script.fantasy': 'Fantasy',
    'script.creative': 'Script Idea',
    'script.creativePlaceholder': 'Please describe your script idea, such as: a love story about time travel, the protagonist unexpectedly returns to the past and meets a young lover...',

    // Annual Member Features
    'membership.annualFeature1': 'Get 150,000 credits',
    'membership.annualFeature2': 'Extra 30,000 credits',
    'membership.annualFeature3': 'Unlimited chats with regular models',
    'membership.annualFeature4': '500 chats with advanced models',
    'membership.annualFeature5': 'Generate 100 images',
    'membership.annualFeature6': 'Generate 25 videos',
    'membership.annualFeature7': 'Priority customer support',
    // Monthly Member Features
    'membership.monthlyFeature1': 'Get 10,000 credits',
    'membership.monthlyFeature2': 'Unlimited chats with regular models',
    'membership.monthlyFeature3': '500 chats with advanced models',
    'membership.monthlyFeature4': 'Generate 100 images',
    'membership.monthlyFeature5': 'Generate 25 videos',
    'membership.monthlyFeature6': 'Standard customer support',
    // Free Member Features
    'membership.freeFeature1': '5 AI chats per day',
    'membership.freeFeature2': 'Basic model access',
    'membership.freeFeature3': 'Standard response speed',
    'membership.freeFeature4': 'Basic features',
    
    // Script missing translations
    'script.creating': 'Creating',
    'script.genre': 'Genre',
    'script.pleaseInputIdea': 'Please input script idea',
    'script.requestFailed': 'Request failed',
    'script.pleaseTryAgain': 'Please try again later',
    
    // Credits and free quota related translations
    'credits.consume': 'Consume',
    'credits.credits': 'credits',
    'credits.consumeCredits': 'Consume {cost} credits',
    'credits.remainingFreeChats': 'Remaining free chats',
    'credits.remainingFreeDocs': 'Remaining free documents',
    'credits.remainingFreePDF': 'Remaining free PDF',
    'credits.remainingFreeImages': 'Remaining free images',
    'credits.remainingFreeVideos': 'Remaining free videos',
    'credits.remainingCredits': 'Remaining credits',
    'credits.recharge': 'Recharge credits',
    'credits.freeQuotaFormat': '{remaining}/{total}',
    
    // Button cost display
    'ui.costCredits': 'Consume {cost} credits',
    'ui.remainingFree': 'Remaining free {type}: {remaining}/{total}',
    'ui.freeChat': 'chats',
    'ui.freeDocument': 'documents',
    'ui.freePDF': 'PDF',
    'ui.freeImage': 'images',
    'ui.freeVideo': 'videos',
    
    // Selector label translations
    'selector.tone': 'Tone',
    'selector.length': 'Length',
    'selector.language': 'Language',
    'selector.translateTo': 'Translate to',
    'selector.budget': 'Budget',
    'selector.pace': 'Pace',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // 从localStorage获取语言设置
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage === 'zh' || savedLanguage === 'en') {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, params?: Record<string, string>) => {
    const currentTranslations = translations[language] || translations.en;
    let text = currentTranslations[key] || key;

    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        text = text.replace(`{${param}}`, value);
      });
    }

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 